sudo: required
dist: trusty

language: java
jdk: oraclejdk8

env:
  - BUILD_NUMBER=9999

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/minecraft/deobfedDeps/providedDummy.jar
  - rm -f  $HOME/.gradle/caches/minecraft/deobfedDeps/compileDummy.jar
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install: chmod +x gradlew
install:
  - ./gradlew --refresh-dependencies
script:
  - ./gradlew ciWriteBuildNumber
  - ./gradlew Forge:test

notifications:
  email: false
